### PR TITLE
#104 PrometheusWebScript: don't ERROR log max request violations during startup

### LINKED ISSUE #104: Prometheus scraping: max number of requests reached during Alfresco startup
Follows PR #100 (issue #70)
Relates to Alfred Telemetry Platform 

In PR #100 we introduced a semaphore to limit the number of concurrent requests to the `/prometheus` endpoint, with a default of maximum one concurrent requests. 

During ACS startup, Prometheus requests are not immediately processed and stack up. Because we allow a maximum of one request by default, we see following error message in the logs:

```
2021-06-09 12:01:20,344  ERROR [extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-24] Exception from executeScript: 05090018 Max number of active requests (1) reached
org.springframework.extensions.webscripts.WebScriptException: 05090018 Max number of active requests (1) reached
        at eu.xenit.alfred.telemetry.webscripts.PrometheusWebScript.execute(PrometheusWebScript.java:44)

```

Possible solutions:

- Increase the default number of maximum allowed concurrent `/prometheus` requests

### PR DESCRIPTION
**Pull request by kerkhofsd**
Fixes #104

### CODE REVIEW

**Review by driesdeproost — APPROVED** [review]

**Review by thijslemmens — APPROVED** [review]

File: alfred-telemetry-platform/src/test/java/eu/xenit/alfred/telemetry/webscripts/PrometheusWebScriptTest.java [hunk 1]
```diff
@@ -33,30 +32,40 @@
...
-        verify(response).setStatus(200);
-        assertThat(out.toString("UTF-8"), is(equalTo(TEST_SCRAPE_TEXT)));
+        webScript.execute(mockedRequest, mockedResponse);
+        verify(mockedResponse).setStatus(200);
+        assertThat(responseOutputStream.toString("UTF-8"), is(equalTo(TEST_SCRAPE_TEXT)));
     }
 
     @Test
-    void execute_maxRequestsReached() {
+    void execute_maxRequestsReached() throws IOException {
```
Comment (thijslemmens) [inline alfred-telemetry-platform/src/test/java/eu/xenit/alfred/telemetry/webscripts/PrometheusWebScriptTest.java:58]: naming conventions?

**Review by thijslemmens — CHANGES_REQUESTED** [review]

**Review by thijslemmens — APPROVED** [review]
